[tool.bumpversion]
current_version = "0.4.0-rc0"
parse = """(?x)
    (?P<major>0|[1-9]\\d*)\\.
    (?P<minor>0|[1-9]\\d*)\\.
    (?P<patch>0|[1-9]\\d*)
    (?:
        -                             # dash separator for pre-release section
        (?P<pre_l>[a-zA-Z-]+)         # pre-release label
        (?P<pre_n>0|[1-9]\\d*)        # pre-release version number
    )?                                # pre-release section is optional
"""
serialize = [
    "{major}.{minor}.{patch}-{pre_l}{pre_n}",
    "{major}.{minor}.{patch}",
]
tag = true
sign_tags = true
tag_name = "v{new_version}"
tag_message = "bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "chore(release): Bump version: {current_version} → {new_version}"
commit_args = "--no-verify"

[tool.bumpversion.parts.pre_l]
values = ["dev", "rc", "final"]
optional_value = "final"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "src/sblex/saldo_ws/shared/version_info.py"
search = "__date__ = \"\\d{{4}}-\\d{{2}}-\\d{{2}}\""
replace = "__date__ = \"{now:%Y-%m-%d}\""
regex = true

[[tool.bumpversion.files]]
filename = "src/sblex/saldo_ws/shared/version_info.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = '## [unreleased]'
replace = '## [{new_version}] - {now:%Y-%m-%d}'
