[tool.poetry]
name = "sblex-server"
version = "0.2.3"
description = "SBLEX server working with FM data."
authors = ["Kristoffer Andersson <kristoffer.andersson@gu.se>"]
license = "MIT"
readme = "README.md"
packages = [{include = "sblex", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.103.2"
jinja2 = "^3.1.2"
opentelemetry-instrumentation-fastapi = "^0.40b0"
opentelemetry-sdk = "^1.17.0"
opentelemetry-instrumentation-logging = "^0.40b0"
json-streams = "^0.12.4"
python-json-logger = "^2.0.7"
asgi-matomo = "^0.4.1"
environs = "^9.5.0"
brotli-asgi = "^1.4.0"
uvicorn = "^0.23.2"
gunicorn = "^21.2.0"
opentelemetry-instrumentation-httpx = "^0.40b0"
httpx = "^0.24.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pytest-cov = "^4.0.0"
black = "^23.1.0"
mypy = "^1.5.0"
pytest-asyncio = "^0.21.0"
asgi-lifespan = "^2.0.0"
python-dotenv = "^1.0.0"
watchfiles = "^0.19.0"
bump2version = "^1.0.1"

[tool.poetry.group.ci]
optional = true

[tool.poetry.group.ci.dependencies]
ruff = "^0.0.292"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
