[tool.poetry]
name = "sblex-server"
version = "0.1.0"
description = "SBLEX server working with FM data."
authors = ["Kristoffer Andersson <kristoffer.andersson@gu.se>"]
license = "MIT"
readme = "README.md"
packages = [{include = "sblex", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
pytest-cov = "^4.0.0"
black = "^23.1.0"
mypy = "^1.1.1"
pytest-asyncio = "^0.21.0"
httpx = "^0.23.3"
asgi-lifespan = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
