[tool.poetry]
name = "sblex-server"
version = "0.2.3"
description = "SBLEX server working with FM data."
authors = ["Kristoffer Andersson <kristoffer.andersson@gu.se>"]
license = "MIT"
readme = "README.md"
packages = [{include = "sblex", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.2"
jinja2 = "^3.1.2"
opentelemetry-instrumentation-fastapi = "^0.38b0"
opentelemetry-sdk = "^1.17.0"
opentelemetry-instrumentation-logging = "^0.38b0"
json-streams = "^0.12.4"
python-json-logger = "^2.0.7"
asgi-matomo = "^0.3.2"
environs = "^9.5.0"
brotli-asgi = "^1.4.0"
uvicorn = "^0.22.0"
gunicorn = "^20.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
pytest-cov = "^4.0.0"
black = "^23.1.0"
mypy = "^1.3.0"
pytest-asyncio = "^0.21.0"
httpx = "^0.24.0"
asgi-lifespan = "^2.0.0"
python-dotenv = "^1.0.0"
watchfiles = "^0.19.0"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
