[http]
[http.middlewares]

[http.middlewares.api-stripprefix.stripPrefix]
prefixes = ["/ws/saldo-ws"]

[http.routers]

[http.routers.app-http]
entryPoints = ["http"]
service = "app"
rule = "PathPrefix(`/ws/saldo-ws`)"
middlewares = ["api-stripprefix"]

[http.services]

[http.services.app]
[http.services.app.loadBalancer]
[[http.services.app.loadBalancer.servers]]
url = "http://127.0.0.1:8000"
